import { HardhatUserConfig } from "hardhat/config";
import { HardhatConfig, MrklTreeConfig } from "hardhat/types/config";
import { HardhatUserConfigValidationError } from "hardhat/types/hooks";

/**
 * This function validates the parts of the HardhatUserConfig that are relevant
 * to the plugin.
 *
 * This function is called from the `validateUserConfig` Hook Handler.
 *
 * @param userConfig The HardhatUserConfig, as exported in the config file.
 * @returns An array of validation errors, or an empty array if valid.
 */
export async function validatePluginConfig(
  userConfig: HardhatUserConfig,
): Promise<HardhatUserConfigValidationError[]> {
  const errors: HardhatUserConfigValidationError[] = [];

  if (userConfig.auditagent) {
    const config = userConfig.auditagent;

    // Validate mode
    if (
      config.mode &&
      !["basic", "advanced", "full"].includes(config.mode as string)
    ) {
      errors.push({
        path: ["auditagent", "mode"],
        message: `Invalid mode: ${config.mode}. Must be one of: basic, advanced, full`,
      });
    }

    // Validate format
    if (
      config.format &&
      !["console", "json", "sarif"].includes(config.format as string)
    ) {
      errors.push({
        path: ["auditagent", "format"],
        message: `Invalid format: ${config.format}. Must be one of: console, json, sarif`,
      });
    }

    // Validate AI provider
    if (
      config.ai?.provider &&
      !["openai", "anthropic", "local"].includes(config.ai.provider as string)
    ) {
      errors.push({
        path: ["auditagent", "ai", "provider"],
        message: `Invalid AI provider: ${config.ai.provider}. Must be one of: openai, anthropic, local`,
      });
    }
  }

  return errors;
}

/**
 * Resolves the plugin config, based on an already validated HardhatUserConfig
 * and a partially resolved HardhatConfig.
 *
 * This function is called from the `resolveUserConfig` Hook Handler.
 *
 * @param userConfig The HardhatUserConfig.
 * @param partiallyResolvedConfig The partially resolved HardhatConfig, which is
 *  generated by calling `next` in the `resolveUserConfig` Hook Handler.
 * @returns The resolved HardhatConfig.
 */
export async function resolvePluginConfig(
  userConfig: HardhatUserConfig,
  partiallyResolvedConfig: HardhatConfig,
): Promise<HardhatConfig> {
  const userMrklTreeConfig = userConfig.auditagent || {};

  // Resolve MrklTree configuration with defaults
  const resolvedMrklTreeConfig: MrklTreeConfig = {
    mode: userMrklTreeConfig.mode || "full",
    playbook: userMrklTreeConfig.playbook,
    rules: userMrklTreeConfig.rules,
    format: userMrklTreeConfig.format || "console",
    output: userMrklTreeConfig.output,
    ai: userMrklTreeConfig.ai
      ? {
          enabled: userMrklTreeConfig.ai.enabled !== false, // default true if ai config exists
          provider: userMrklTreeConfig.ai.provider || "openai",
          model: userMrklTreeConfig.ai.model,
          temperature: userMrklTreeConfig.ai.temperature,
          maxTokens: userMrklTreeConfig.ai.maxTokens,
        }
      : undefined,
  };

  return {
    ...partiallyResolvedConfig,
    auditagent: resolvedMrklTreeConfig,
  };
}
